---
title: "Random Walks pictures"
output: html_notebook
---


# Random Walks

```{r}
library(tidyverse)

T <- 15
nsim <- 3

single <- function(T) {
  dx = sample(c(-1,1), replace = TRUE, T)
  return(c(0,cumsum(dx)))
}

S = data.frame(t(replicate(nsim, single(T))))

variable_name_X <- function(i){
  paste("X",toString(i),sep="")
}

variable_name_i <- function(i) return(i)

colnames(S) = lapply(0:T, variable_name_i)

S = S %>% 
  mutate(omega = rownames(S)) # this way it is a <chr> and that is good!, makes it a factor 

```


```{r}

# put it in long form for plotting
L = S %>% 
  pivot_longer(-omega, names_to = "t", values_to = "X") 
L$t = as.numeric(L$t) # because columns names become characters
L$X = L$X + rnorm(length(L$X), sd = 0.1) # jitter

```


```{r}
ggplot(L, aes(x=t, y=X, group = omega))+geom_line()+theme_bw()+xlab("")+ylab("")+
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())+
          coord_fixed()
          
```

