# Solutions to problems in Chapter 1

```{exercise}
Compute the following (your answer should be a decimal number):
  
  a) $1/238746238746$ 
  b) $2^{45}$
  c) $3^{28}$ 
  d) $\sqrt{15}$
  e) $\cos(\pi/8)$
  f) $e^2$
  g) $\log(2)$ (the base is $e$)
  h) $\log_{10}(2)$ (the base is $10$)
  i) $\sqrt[3]{ \frac{1342.16-2.18}{(3 \pi +4.12)^2}}$
```

**Solution.**

Remember, pa`xrentheses around the whole expression tell R to print out the result

```{r}
(1/238746238746)
(2^(45)) # this is the same as 2**45
(3^(28))
(sqrt(15))
(cos(pi/8))
(exp(2))
(log(2))
(log10(2))
(((1342.16-2.18)/(3*pi +4.12)^2)^(1/3))
```


```{exercise}
\ \newline 

1. Define two variables $a$ and $b$ with values $3$ and $4$ and "put" their product into a variable called $c$. Output the value of $c$.

2. Define two vectors $x$ and $y$ of length $3$, such that the components of $x$ are $1,2,3$ and the components of $y$ are $8,9,0$. Ouput their (componentwise) sum.

3. Define a $2\times 2$ matrix $A=\begin{pmatrix} 1 & 2 \\ -1 & 3 \end{pmatrix}$.

4. Compute the matrix square $A^2$. 
```

**Solution.**

```{r}
a=3
b=4
(c=a*b)

x=c(1,2,3)
y=c(8,9,0)
(x+y)

(A=matrix(c(1,2,-1,3), byrow=TRUE, nrow=2))

(A %*% A)

```


```{exercise}
\ \newline 

1. Construct a vector $x$ which contains all numbers from $1$ to $100$.

2. Construct a vector $y$ which contains *squares* of all numbers between $20$ and $2000$.

3. Construct a vector $z$ which contains only those components of $y$ whose values are between $400,000$ and $500,000$.

4. Compute the average (arithmetic mean) of all the components of $z$. There is an R function that does that for you - find it!
```  

**Solutions.**

1.
```{r}
x = 1:100
```

2.
```{r}
y = (20:2000)^2
```

3.

```{r}
(z=y[y>400000 & y<500000])

```

4.
```{r}
(mean(z))

```


```{exercise} 
\ \newline 

1. Write a function that takes a numerical argument $x$ and returns $5$ if $x\geq 5$ and $x$ itself otherwise.

2. Write a function that returns `TRUE` (a logical value) if its argument is between $2$ and $3$ and `FALSE` otherwise. 

3. (Extra credit) Write a function that takes two equal-sized vectors as arguments and returns the angle between them in degrees. For definiteness, the angle between two vectors is defined to be $0$ when either one of them is $(0,0,\dots,0)$. 
```

**Solution.**

1.
```{r}
f = function(x) {
  if (x>5) {
    return(5)
  } else {
    return(x)
  }
}
```
This could be made much shorter using the function `ifelse`:
```{r}
f = function(x)
  ifelse(x>5,5,x)
```


2.
```{r}
g <- function(x) {
  if (x>2 & x<3) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

# more R-ic (what's "Pythonic", but for R?)
g <- function(x) 
  x>2 & x<3

 
```

3.
```{r}
angle <- function(x,y) {
  length_x = sqrt(sum(x**2))
  length_y = sqrt(sum(y**2))
  if (length_y == 0 | length_x == 0) {
    return(0)
  } else {
    inn_prod = sum(x*y)
    cos_alpha = inn_prod/(length_x * length_y)
    return(acos(cos_alpha)/pi*180)
  }
}

# some testing

# should be 0
(angle( c(1,1), c(1,1) ) )

# should be 0
(angle( c(0,0), c(1,2)))

# should be 45
(angle( c(0,1), c(1,1)))

# should be 90
(angle( c(1,0), c(0,1)))


```


