# Random Walks

```{r}
T <-  20
nsim <- 100

single <- function(T) {
  dx = sample(c(-1,1), replace = TRUE, T)
  return(c(0,cumsum(dx)))
}

S = data.frame(t(replicate(nsim, single(T))))

variable_name <- function(i){
  paste("X",toString(i),sep="")
}

colnames(S) = lapply(0:T, variable_name)
```


```{r}

T <- 30
single <- function(T) {
  dx = sample(c(-1,1), replace = TRUE, T)
  return(c(0,cumsum(dx)))
}
  
df = data.frame(t = 0:T, X = as.vector(t(single(T))))


accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

df = df %>% accumulate_by(~t)

fig <- df %>% plot_ly(
  x = ~t, 
  y = ~X, 
  frame = ~frame,
  type = 'scatter', 
  mode = 'lines', 
  fillcolor='rgba(114, 186, 59, 0.5)',
  line = list(color = 'rgb(114, 186, 59)')
)
fig <- fig %>% layout(
  title = "A trajectory of a random walk",
  yaxis = list(
    title = "X", 
    range = c(-10,10), 
    zeroline = F,
    tickprefix = ""
  ),
  xaxis = list(
    title = "t", 
    range = c(0,T), 
    zeroline = T, 
    showgrid = T
  )
) 
fig <- fig %>% animation_opts(
  frame = 10, 
  transition = 0, 
  redraw = FALSE
)

fig <- fig %>% animation_slider(
  hide = T
)
# fig <- fig %>% animation_slider(
#   currentvalue = list(
#     prefix = "t "
#   )
# )

fig
```

